Adds behavior to pan the Bottom Sheet modal on scroll
wordpress-mobile/WordPressUI-iOS pull request #68
Opened 2020-05-14 17:23 UTC by bjtitus

WPiOS PR: 

This adds behavior to the Bottom Sheet modal to pan up and down when scrolling the content in `scrollableView`.

<a href="https://user-images.githubusercontent.com/3250/81965385-394ad680-95d5-11ea-8b08-add9e3e7dae0.gif"><img src="https://user-images.githubusercontent.com/3250/81965385-394ad680-95d5-11ea-8b08-add9e3e7dae0.gif" width="300"></a>

#### Testing
- Use the WordPress iOS PR
- Navigate to the Reader screen and tap the Filter button
- Filter modal begins compact but expands upon scrolling the content up
- Filter modal switches to compact on scrolling down
- Filter modal dismisses on scrolling further down
- Filter modal will expand or dismiss on "flinging" while scrolling up or down

2020-05-15 15:57 UTC, emilylaguna requested changes
Heya, thanks for doing this. It's working pretty well on WordPress. 

When I tested the WPUI branch on WooCommerce who also uses the bottom sheet it looks like it breaks the scrolling for some reason. See the gif below:

<img src="https://user-images.githubusercontent.com/793774/82070119-22fe5280-9689-11ea-87a9-9d71af389abb.gif" width="30%" />

2020-05-15 20:53 UTC, bjtitus commented
@emilylaguna Thanks for catching that! It looks like there was an issue with checking for a `nil` `scrollableView` that lead to this issue in WooCommerce. Should be fixed in the latest commit.

2020-05-18 15:50 UTC, bjtitus commented
Added details about minor known issues which we think can be fixed in a follow up PR in the interest of making sure this ships alongside the WordPress IA changes in 14.9.

2020-05-19 13:53 UTC, emilylaguna approved these changes
Working well for me!

2020-05-19 15:30 UTC, merged