Update the bottom sheet's presented view frame on view layout
wordpress-mobile/WordPressUI-iOS pull request #80
Opened 2020-12-17 00:09 UTC by yaelirub

Fixes: https://github.com/wordpress-mobile/WordPress-iOS/issues/15531
`containerViewWillLayoutSubviews` gets called when we switch between categories and tags pickers to prepublishing view. 
This PR sets the frame of the presented in that method
![prepublishing_nudges](https://user-images.githubusercontent.com/1335657/102420466-0f1c2580-3fb7-11eb-885f-1b859315bedf.gif)

2020-12-17 01:07 UTC, momo-ozawa approved these changes
LGTM!

2020-12-17 01:07 UTC, momo-ozawa commented
### Side note
Might be nice to adjust the bottom constraint for the `Publish Now` button it has padding. Seems to be an issue on devices like the iPhone SE 2nd gen. Looks fine on iPhone 12 Pro. Maybe an issue with safe area??

iPhone SE 2nd gen | iPhone 12 Pro
--- | ---
![Screen Shot 2020-12-17 at 10 00 51](https://user-images.githubusercontent.com/6711616/102424597-daf44380-404e-11eb-9345-9367137c579f.png) | ![Screen Shot 2020-12-17 at 10 06 20](https://user-images.githubusercontent.com/6711616/102424926-94531900-404f-11eb-8c5a-f058dc3b1e04.png)

2020-12-17 17:35 UTC, emilylaguna requested changes
Hmm, I am seeing the view jump to full size when switching to the categories view.

| Lots of categories | 1 category|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/793774/102522195-f3228d80-4063-11eb-899e-94fd2a83c8aa.gif" width="" />|<img src="https://user-images.githubusercontent.com/793774/102522277-12211f80-4064-11eb-8bb1-0330a273adca.gif" width="80%" />|

2020-12-21 21:13 UTC, emilylaguna commented
Closing in favor of: https://github.com/wordpress-mobile/WordPressUI-iOS/pull/81

2020-12-21 21:13 UTC, closed without merging